baseURL = "https://hartrussell.com"
languageCode = "en-us"
title = "Mindful Drivel"
theme = "hEart"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	#subtitle = "Some Thoughts"
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	author = "Hart Russell"
	description = "Personal website of Hart Russell"

[Author]
    name = "Hart Russell"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Pictures"
url = "/image-gallery"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/HartR"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/hartcranerussell"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/hortisimo"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:hartcranerussell@gmail.com"

[[params.social]]
name = "goodreads"
icon = "book-open"
url = "https://www.goodreads.com/user/show/38546479-hart-russell"

[[params.social]]
name = "Calendar"
icon = "calendar"
url = "https://calendar.google.com/calendar?cid=aG9ydGlzaW1vQGdtYWlsLmNvbQ"

[taxonomies]
   tag = "tags"

enableRobotsTXT = true
canonifyURLs = true
